// Shared navigation and visual identity for the authored demos.
export const systems = [
  [
    "biome",
    "Biome",
    "Terrain & placement",
    "index.html#biome",
    "#dcf68b",
    "#111d18",
    "#1b2d23",
  ],
  [
    "flux",
    "Flux",
    "Motion trails",
    "index.html#flux",
    "#91e8de",
    "#102024",
    "#193238",
  ],
  [
    "signal",
    "Signal",
    "Combat telegraphs",
    "signal.html",
    "#ffb99c",
    "#251a19",
    "#352724",
  ],
  [
    "latch",
    "Latch",
    "Contextual interactions",
    "latch.html",
    "#efd29a",
    "#211f16",
    "#302e22",
  ],
  [
    "loom",
    "Loom",
    "Splines & geometry",
    "loom.html",
    "#95d8ed",
    "#13212a",
    "#20333f",
  ],
  [
    "satchel",
    "Satchel",
    "Inventory & crafting",
    "play.html?kit=satchel",
    "#e7c18a",
    "#211d17",
    "#342b20",
  ],
  [
    "chatter",
    "Chatter",
    "Branching dialogue",
    "play.html?kit=chatter",
    "#edafd6",
    "#251c29",
    "#37293c",
  ],
  [
    "trailmark",
    "Trailmark",
    "Quests & objectives",
    "trailmark.html",
    "#b9e5bb",
    "#15221c",
    "#23372a",
  ],
  [
    "wayfinder",
    "Wayfinder",
    "Grid pathfinding",
    "wayfinder.html",
    "#c6bce9",
    "#1d1b2c",
    "#2c2941",
  ],
  [
    "spring",
    "Spring",
    "Responsive motion",
    "spring.html",
    "#99543d",
    "#f3f3e9",
    "#e8e9df",
  ],
  [
    "parcel",
    "Parcel",
    "Loot & probability",
    "parcel.html",
    "#f1c674",
    "#252018",
    "#372f23",
  ],
  [
    "tempo",
    "Tempo",
    "Charges & cooldowns",
    "tempo.html",
    "#bfc6f1",
    "#191e30",
    "#292f45",
  ],
  [
    "ledger",
    "Ledger",
    "Stats & loadouts",
    "ledger.html",
    "#e8b579",
    "#101b24",
    "#192934",
  ],
  [
    "keepsake",
    "Keepsake",
    "Save migration",
    "keepsake.html",
    "#beadf3",
    "#161727",
    "#232337",
  ],
  [
    "sift",
    "Sift",
    "Asset validation",
    "sift.html",
    "#b7ed87",
    "#102326",
    "#193438",
  ],
  [
    "mothlight",
    "Mothlight",
    "Playable adventure",
    "templates/mothlight/",
    "#eed997",
    "#17232f",
    "#253442",
  ],
  [
    "afterglow",
    "Afterglow",
    "Playable combat",
    "templates/afterglow/",
    "#a7e9d7",
    "#132b35",
    "#18343c",
  ],
];
